### ISSUE TITLE
Type mixed includes every other type

### ISSUE THREAD

**Issue by szepeviktor** [SerafimArts/Pipe#2]
```
OperatorsTrait.php:51:     * @param int|string|mixed $status
OperatorsTrait.php:60:     * @param int|string|mixed $status
OperatorsTrait.php:69:     * @param mixed|null $value
helpers.php:14:     * @param mixed|null $value
```

so there is no `mixed|anything`

**Comment by SerafimArts** [comment]
Fixed https://github.com/SerafimArts/Pipe/commit/7cc42f38d294541f92b775ce989cd500b0f5b040

**Comment by szepeviktor** [comment]
@SerafimArts On many place it is still `blablabla|mixed`
e.g. https://github.com/SerafimArts/Pipe/blob/master/src/OperatorsTrait.php#L52

**Comment by SerafimArts** [comment]
@szepeviktor maybe I misunderstood your request

**Comment by szepeviktor** [comment]
Yes, this is rational.
But when you recognize a certain value can by any type simply put `mixed` there.

**Comment by SerafimArts** [comment]
I think it's worth getting rid of the `mixed` type, leaving only strict types. As example argument of `die` method can not be an array.

**Comment by szepeviktor** [comment]
👍 for _strict types_

**Comment by SerafimArts** [comment]
I just looked - there are problems. In particular, transferring a placeholder. For example:
```php
pipe(255)->die(_);
```

`_` itself is neither a string nor a number. This is a special data type (symbol) based on a resource for uniqueness.

**Comment by szepeviktor** [comment]
`_` is a syntax error,
`$_` is a variable :)

**Comment by SerafimArts** [comment]
nope =) This is placeholder in some functional languages (and this package).

```php
var_dump(is_placeholder(_));
```

**Comment by SerafimArts** [comment]
> 👍 for strict types

Like this https://github.com/SerafimArts/Pipe/commit/2a3ed4ca8fa98df17cd24451b3ea867260d862e9 ?

**Comment by szepeviktor** [comment]
How could you process `_`?

```
$ php -r 'var_dump(_);'
PHP Warning:  Use of undefined constant _ - assumed '_' (this will throw an Error in a future version of PHP) in Command line code on line 1
```

**Comment by szepeviktor** [comment]
I see :)
You use it for documentation!

**Comment by SerafimArts** [comment]
> How could you process _?

This functionality is part of the library, not the language
